Repository Riksrevisjonen/pioneeR, pull requests merged in 2023-12, with the labels that each got.

#46 Add pkgdown
  .Rbuildignore
  .github/.gitignore
  .github/workflows/pkgdown.yaml
  .gitignore
  _pkgdown.yml
Labels: Type: 2-Enhancement, Priority: 2-High

#59 Set 0 as first interval, and take absoulte value
  inst/app/R/utils.R
Labels: Type: 1-Bug, Priority: 2-High

#72 57 UI updates
  DESCRIPTION
  NEWS.md
  inst/app/R/fct_dea-boostrap.R
  inst/app/R/fct_file-functions.R
  inst/app/R/mod_file-upload.R
  inst/app/server.R
  inst/app/ui.R
  inst/app/www/style.css
Labels: Type: 1-Bug, Type: 2-Enhancement, Priority: 2-High, Release
